# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('context', models.TextField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Navigation'),
        ),
    ]
