# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 10:51
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='bads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='context',
            name='goods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='context',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='context',
            name='shortcontext',
            field=models.TextField(default=datetime.datetime(2017, 1, 22, 10, 51, 57, 378475), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='context',
            name='times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='context',
            name='context',
            field=DjangoUeditor.models.UEditorField(),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Context'),
        ),
    ]
